set(INSTALL_ROOT_DIR $ENV{INSTALL_ROOT_DIR})

set(CMAKE_INSTALL_PREFIX "${INSTALL_ROOT_DIR}/${PROJECT_NAME}/${CMAKE_SYSTEM_NAME}" CACHE PATH "..." FORCE)

include(GNUInstallDirs)
set (SecurityLib SecurityLib)
install (TARGETS ${SecurityLib}
EXPORT SecurityLib
LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

include(CMakePackageConfigHelpers)